# statefulset-redis.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-redis
spec:
  serviceName: "stateful-redis"
  replicas: 1
  selector:
    matchLabels:
      app: stateful-redis
  template:
    metadata:
      labels:
        app: stateful-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
