# stateless-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stateless-nginx
  template:
    metadata:
      labels:
        app: stateless-nginx
    spec:
     containers:
     - name: nginx
       image: nginx:latest
       ports:
       - containerPort: 80
       env:
       - name: REDIS_HOST
         value: "stateful-redis-service"
       - name: REDIS_PORT
         value: "6379"

